[build]
  command = "npm run generate"
  publish = "src/base/dist"

[build.environment]
  NODE_VERSION = "24"
  SECRETS_SCAN_ENABLED = "false"

[dev]
  command = "npm run dev:nuxt"
  targetPort = 9229
  port = 3000
  framework = "#custom"
  autoLaunch = false
  jwtRolePath = "app_metadata.authorization.roles"
